name: DEPLOY
on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
          yarn
          yarn build
    - name: rsync deployments
      uses: burnett01/rsync-deployments@4.0
      with:
        switches: -a --delete
        path: build/
        remote_path: /usr/local/caddy/www/file/
        remote_host: arslan2012.tech
        remote_user: root
        remote_key: ${{ secrets.DEPLOY_KEY }}

